# Generated by Django 4.2.3 on 2023-07-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_first_name', models.CharField(max_length=30)),
                ('sender_last_name', models.CharField(max_length=30)),
                ('receiver_first_name', models.CharField(max_length=30)),
                ('receiver_last_name', models.CharField(max_length=30)),
                ('massage', models.CharField(max_length=1000)),
                ('subject', models.CharField(max_length=100)),
                ('creation_date', models.DateField()),
            ],
        ),
    ]
