# Generated by Django 4.2.3 on 2023-07-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='read_massage',
            field=models.BooleanField(default=False),
        ),
    ]
